### ISSUE TITLE
Clarify Overwriting Chart Values

### ISSUE THREAD

**Issue by masus04** [mittwald/go-helm-client#22]
I was trying to figure out how to overwrite default values from the chart repository. I have to apply dynamic values as we plan on using go-helm-client as part of a self service solution.

Looking at the interfaces, I assume I can pass a string representing the overwritten chart values to the ChartSpec:
`chartSpec.ValuesYaml = "..."`
Is this assumption correct and if so, how does this string have to be formatted?
Also, do these values overwrite the default values and are the remaining default values retained?

Thank you and best regards

**Comment by elenz97** [comment]
Hey @masus04,

thanks for your question!

First off, you're right on all your assumptions - default chart values can be overwritten by setting a custom `string` value on `chartSpec.valuesYaml` while the remaining (default) values are retained.

Regarding formatting i think it's best to give an example, assuming you use the conventional way of importing the `go-helm-client` package via `go get`:

In the [harbor-operator](https://github.com/mittwald/harbor-operator/) project we're utilizing this client to realize automated helm chart installations.
As we also needed to override default values, we extended our specifications to [inline the `chartSpec`](https://github.com/mittwald/harbor-operator/blob/a09bc84eb92e2d968d931d64611adb7fbe230fd5/apis/registries/v1alpha2/instance_types.go#L83).

In the [helm chart template](https://github.com/mittwald/harbor-operator/blob/a09bc84eb92e2d968d931d64611adb7fbe230fd5/deploy/helm-chart/harbor-operator/templates/instance/instance.yaml#L26) we specify the _literal_ string content (by using the `|` indicator), using [nindent 6](https://helm.sh/docs/chart_template_guide/function_list/#nindent) to indent each line by that amount.
The string content may be passed in programmatically, or - for the sake of completeness - in plain .yaml [like here](https://github.com/mittwald/harbor-operator/blob/master/deploy/helm-chart/harbor-operator/values.yaml#L82).

HTH

**Comment by masus04** [comment]
Thank you for your quick reply @elenz97 

So if I understand your examples correctly, I can simply pass a yaml formatted string to the helmclient.ChartSpec struct like this:
`helmclient.ChartSpec{
		ValuesYaml:  registryValuesYamlString,
                { ... }
`

**Comment by elenz97** [comment]
Hey @masus04,
you're absolutely right :wink: 
Just for reference, this may be a more practicable example (expanded from our [GoDoc example](https://pkg.go.dev/github.com/mittwald/go-helm-client#HelmClient.InstallOrUpgradeChart)):

```go
func InstallOrUpgradeChart() {
	// Define custom values.yaml overrides
	exampleValuesYaml := `deployments:
  etcdOperator: true
  backupOperator: false
`
	// Define the chart to be installed
	chartSpec := ChartSpec{
		ReleaseName: "etcd-operator",
		ChartName:   "stable/etcd-operator",
		Namespace:   "default",
		UpgradeCRDs: true,
		Wait:        true,
		ValuesYaml:  exampleValuesYaml,
	}

	if err := helmClient.InstallOrUpgradeChart(context.Background(), &chartSpec); err != nil {
		panic(err)
	}
}
