### ISSUE TITLE
Support Retrieving installed Charts

### ISSUE THREAD

**Issue by masus04** [mittwald/go-helm-client#23]
There currently does not seem to be any way to retrieve installed charts and their respective values.
There is a method called `chartIsInstalled`, which checks if a chart is currently installed, but it is private.

Is there currently a way to retrieve information about installed charts using the public interface? If not, is it possible to extend it to support those use cases?

**Comment by elenz97** [comment]
Hey @masus04!

Thanks for opening this issue.

> Is there currently a way to retrieve information about installed charts using the public interface?

As of now, information about installed charts is retrieved _implicitly_.
For example when calling [`InstallOrUpgradeChart()`](https://github.com/mittwald/go-helm-client/blob/34254903a3efd5f7710974b4496c4f2b03546acc/client.go#L197), [`chartIsInstalled()`](https://github.com/mittwald/go-helm-client/blob/34254903a3efd5f7710974b4496c4f2b03546acc/client.go#L563) is called to determine existence of a helm release.

> If not, is it possible to extend it to support those use cases?

I suppose you are looking for the functionality of [`helm list`](https://helm.sh/docs/helm/helm_list/#helm-list) in this client? Please let us know.

As `go-helm-client` does not yet utilize the `list` action, I think it would be a good extension overall.

**Comment by masus04** [comment]
Thank your for your reply @elenz97 

I am using the helm client as part of an Open Service Broker and would like to read installed charts explicitly in order to perform the following actions:
- Check if a perticular resource is already installed (probably using an 'helm list' equivalent, or simply chartIsInstalled(), but publicly available)
- Display information about an installed chart (similar to 'helm get values')
- Generate an updated chart from updated data provided by the user and already available data from the currently installed chart and upgrade.

The most important of these the first one, where I would really only need chartIsInstalled() to be public.
