### ISSUE TITLE
Need guidance in building chart programatically

### ISSUE THREAD

**Issue by jaingaurav001** [mittwald/go-helm-client#24]
Can this library be used to create helm chart programmatically ? If not any guidance on how that can be done by doing code changes to this library or some other way?

**Comment by elenz97** [comment]
Hey @jaingaurav001

> Can this library be used to create helm chart programmatically ?

What exactly do you mean by _creating_ a helm chart? Are you looking for the functionality of `helm create`? Please expand on your question.

On a side note: This repository's goal is to provide an easy way for users to programmatically _interact_ with helm, e.g. installing or updating a helm release by a provided chart specification.
Please refer to our [examples](https://pkg.go.dev/github.com/mittwald/go-helm-client#Client) to get a more in-depth view on what the client provides.
