### ISSUE TITLE
acr helm pull

### ISSUE THREAD

**Issue by DvpDevelop** [mittwald/go-helm-client#30]
hi guys, 

im trying to install a chart from acr. 
When execute repo add and update it works well but when to go to try install a chart gives 401
    
    err = helmClient.AddOrUpdateChartRepo(chartRepo); err != nil { // it works
		    panic(err)
	    }

	err = helmClient.UpdateChartRepos() // it works
	if err != nil {
		return err
	}

	// Define the chart to be installed
	chartSpec := helmclient.ChartSpec{
		ReleaseName: deploy.ReleaseName,
		ChartName:   fmt.Sprintf("%s/%s", deploy.InfoRegistry.RepositoryName, deploy.ChartName),
		Namespace:   "default",
		UpgradeCRDs: false,
		Wait:        true,
		Force: true,
	}

	if _ , err := helmClient.InstallOrUpgradeChart(context.TODO(), &chartSpec); err != nil { // fails
		logrus.Error(err)
		return err
	}
 

thks.
awesome project !!

**Comment by jkmw** [comment]
Hi DvpDevelop,

am I correct in assuming that you include credentials for your repo?

Since [helm 3.6.1](https://github.com/helm/helm/commit/17ed9c4cd3c61290587a22953e5359af5ecccaa2) it is necessary to give the repo `PassCredentialsAll = true`:

```go
chartRepo := repo.Entry{
    Name:               "my-repo",
    URL:                "https://helm.mittwald.de"
    Username:           "username",
    Password:           "my-secret-password",
    PassCredentialsAll: true,
}
err := helmClient.AddOrUpdateChartRepo(chartRepo)
```
I hope this will help you
