### ISSUE TITLE
Breaking changes, upgrading from 0.5.0 -> 0.7.0

### ISSUE THREAD

**Issue by JVecsei** [mittwald/go-helm-client#33]
Hey,

after upgrading to the new version 0.7.0, my existing project did not work anymore.
This was related to a bug introduced in `helm 3.6.1` and fixed in version `3.6.1`.

> The security fix released in v3.6.1 caused a bug to surface that was previously only an issue in uncommon situations. v3.6.2 provides a solution to this bug

https://github.com/helm/helm/releases/tag/v3.6.2

Upgrading to the newest patch might save others some time 👍

**Comment by elenz97** [comment]
Hey @JVecsei,

thanks for pointing out, a new release is en route :+1:

**Comment by elenz97** [comment]
@JVecsei 
The [`v0.8.0`](https://github.com/mittwald/go-helm-client/releases/tag/v0.8.0) release includes an update of the underlying helm dependency. 
Install it via `go get github.com/mittwald/go-helm-client@v0.8.0`.
If you have any other questions, feel free to open a [new issue](https://github.com/mittwald/go-helm-client/issues/new)!

**Comment by JVecsei** [comment]
@elenz97 
Thanks for the quick response & fix! 👍
