### ISSUE TITLE
Memory leak in InstallOrUpgradeChart method

### ISSUE THREAD

**Issue by elenz97** [mittwald/go-helm-client#41]
Repeatedly calling the client method `InstallOrUpgradeChart()` (on whatever chart resource) will result in an increase of used memory.

The behaviour can be reproduced using the below example (which installs/upgrades a goharbor instance):

```go
func main() {
	fmt.Println(os.Getpid()) // Pid used to observe information from /proc/[pid]/status

	ctx := context.Background()

	k, err := ioutil.ReadFile("/path/to/kubeconf")
	if err != nil {
		panic(err)
	}

	cl, _ := helmclient.NewClientFromKubeConf(&helmclient.KubeConfClientOptions{
		Options:     &helmclient.Options{Debug: true, Namespace: "test"},
		KubeContext: "kind",
		KubeConfig:  k,
	})

	cl.AddOrUpdateChartRepo(repo.Entry{
		Name:                  "harbor",
		URL:                   "https://helm.goharbor.io",
		PassCredentialsAll:    true,
	})

	chart := &helmclient.ChartSpec{
		ReleaseName: "test",
		ChartName:   "harbor/harbor",
		Namespace:   "test",
		Version:     "1.7.3",
		Timeout:     5 * time.Second,
		MaxHistory:  1,
	}

	for i := 0; i < 1000; i++ {
		_, err := cl.InstallOrUpgradeChart(ctx, chart)
		if err != nil {
			panic(err)
		}

	}
}
```
Observing the `VmRSS` output from `/proc/[pid]/status` shows a quick memory usage increase (`watch grep VmRSS /proc/[pid]/status`)

Following the program's calls, one quick assumption was that the newly introduced channels in helm's [`pkg/action/upgrade.go`](https://github.com/helm/helm/blob/main/pkg/action/upgrade.go#L323) lack a `close()` call. Adding the missing calls and retrying it with a patched `helm` version did not confirm this however.

This issue needs further investigation, as it is unclear wether the actual bug is contained in `go-helm-client` or in `helm` itself.

**Comment by jkmw** [comment]
fixed by helm/helm#10439
