### ISSUE TITLE
Resources are always deployed in the "default" namespace

### ISSUE THREAD

**Issue by yxzzzxh** [mittwald/go-helm-client#46]
Hi. I am testing "InstallOrUpgradeChart" function.
![image](https://user-images.githubusercontent.com/36444454/140876085-4d6b0cdf-de73-4685-b674-755fa9ac6c22.png)
I changed ChartSpec.Namespace(test1, test2 .etc) but resources are always deployed in the "default" namespace. 
I used [this chart ](https://github.com/argoproj/argocd-example-apps/tree/master/helm-guestbook)

**Comment by elenz97** [comment]
Hey @yxzzzxh, thanks for opening the issue!

Could you explain (maybe in a small code example) how you constructed the client itself (for example, by [REST config](https://github.com/mittwald/go-helm-client/blob/master/client_test.go#L25) or by [kubeconfig](https://github.com/mittwald/go-helm-client/blob/master/client_test.go#L43)) and show what values were provided in its `helmclient.Options`?

**Comment by yxzzzxh** [comment]
Thank you for your reply.

I constructed the client itself by REST config
And I set values in helmclient.RestConfClientOptions like this.
![image](https://user-images.githubusercontent.com/36444454/141050573-f41e92dc-7450-4408-a171-479460154e22.png)

**Comment by elenz97** [comment]
Hey @yxzzzxh 

it seems like the client you constructed lacks the `Namespace` field, which configures in which namespace the _client_ operates.
The `Namespace` that is configurable via `ChartSpec` only affects the created helm release, which led to the unexpected behavior you experienced. 

> I changed ChartSpec.Namespace(test1, test2 .etc) but resources are always deployed in the "default" namespace.

While the helm release itself (output of `helm ls [...]`) should have been installed in the desired namespace (like test1, test2, ...), the resources contained in this helm release were not. As the configured namespace was an empty string, helm defaulted the namespace to `default`.

To get you started, please try constructing the client with the below `RestConfClientOptions`:

```go
[...]
restOpts := &helmclient.RestConfClientOptions{
  Options: &helmclient.Options{
	  Namespace:        "test",
	  RepositoryConfig: "/tmp/.helmcache",
	  RepositoryCache:  "/tmp/.helmrepo",
	  Debug:            true,
	  Linting:          true,
  },
  RestConfig: restConf,
}
```

I'll make sure to update our client examples to better explain the above :+1: 

HTH
