### ISSUE TITLE
can not install 

### ISSUE THREAD

**Issue by safetylab** [mittwald/go-helm-client#49]
go 1.17- pls help
go get github.com/mittwald/go-helm-client
package oras.land/oras-go/pkg/auth: unrecognized import path "oras.land/oras-go/pkg/auth": reading https://oras.land/oras-go/pkg/auth?go-get=1: 404 Not Found
package oras.land/oras-go/pkg/auth/docker: unrecognized import path "oras.land/oras-go/pkg/auth/docker": reading https://oras.land/oras-go/pkg/auth/docker?go-get=1: 404 Not Found
package oras.land/oras-go/pkg/content: unrecognized import path "oras.land/oras-go/pkg/content": reading https://oras.land/oras-go/pkg/content?go-get=1: 404 Not Found
package oras.land/oras-go/pkg/context: unrecognized import path "oras.land/oras-go/pkg/context": reading https://oras.land/oras-go/pkg/context?go-get=1: 404 Not Found
package oras.land/oras-go/pkg/oras: unrecognized import path "oras.land/oras-go/pkg/oras": reading https://oras.land/oras-go/pkg/oras?go-get=1: 404 Not Found

**Comment by elenz97** [comment]
Hey @safetylab 

it seems like this is just a local issue you have on your machine or with your ISP.
Anyways, i could successfully test importing `go-helm-client` in a test go project:

```
$ go mod init test
$ go get github.com/mittwald/go-helm-client
```

**Comment by elenz97** [comment]
Closing this as there has not been any recent activity. Feel free to re-open.
