### ISSUE TITLE
go get fails because of gnostic openapiv2 repo

### ISSUE THREAD

**Issue by HendrikLeier** [mittwald/go-helm-client#85]
when trying to run `go get github.com/mittwald/go-helm-client` the following error occurs

`../../go/pkg/mod/k8s.io/kubectl@v0.23.1/pkg/util/openapi/openapi.go:49:37: cannot use doc (type *"github.com/googleapis/gnostic/openapiv2".Document) as type *"github.com/google/gnostic/openapiv2".Document in argument to "k8s.io/kube-openapi/pkg/util/proto".NewOpenAPIData`

https://github.com/kubernetes/client-go has/had the same issue https://github.com/kubernetes/client-go/issues/1075. Seems to have something to do with google changing paths from  `https://github.com/googleapis/gnostic` to `https://github.com/google/gnostic`

**Comment by HendrikLeier** [comment]
Didn't realize that I had the 0.23.0 client-go in sum file, that caused this issue.

**Comment by shubham-cmyk** [comment]
This problem is from the Client-go library. 

Reference : https://github.com/kubernetes/client-go/issues/1075
