### ISSUE TITLE
How to initialize NewClientFromKubeConf on Google Cloud's GKE

### ISSUE THREAD

**Issue by masus04** [mittwald/go-helm-client#89]
I am trying to create a Client using the **NewClientFromKubeConf** factory but keep getting errors.

If I try to simply pass an empty **KubeConfClientOptions** I get the following error:
```bash
panic: kubeconfig missing
```
Even though my kubeconfig is located under **~/.kube/config** and **$KUBECONFIG** is set accordingly.

So instead I tried passing the **KubeConfig** parameter to **KubeConfClientOptions**:
```golang
kubeConfig, err := os.ReadFile(kubeConfigPath)
checkErr(err)

clientOptions := &helmclient.KubeConfClientOptions{
    KubeConfig: kubeConfig,
}
```

**kubeConfig** properly contains the kubeconfig file as []byte, but I receive the following error anyway:
```bash
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x243b3d6]
```

With a StackTrace that points to this line:
```golang
client, err := helmclient.NewClientFromKubeConf(clientOptions)
```

Am I misunderstanding something?

**Comment by masus04** [comment]
@zvonkok That did the trick, thank you :+1: 

Now I'm running into the next error that I don't know how to solve:
```
panic: Kubernetes cluster unreachable: no Auth Provider found for name "gcp"
```

Is there any chance you have a solution for that as well?

**Comment by zvonkok** [comment]
Add this to your imports: 

```
_ "k8s.io/client-go/plugin/pkg/client/auth/gcp" // register GCP auth provider
```

**Comment by masus04** [comment]
Great, thank you very much!

**Comment by masus04** [comment]
I think error handling messages could be slightly improved: Similar to how a readable error is thrown when **KubeConfig** is not passed, the same could be donw for **Options**. Or simply use a reasonable default instead of the current error that is hard to interpret.
